name: api-scout
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.13
  - pip=23.3.1
  - python=3.10.13
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2024a
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - cachetools==5.3.3
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - flatbuffers==23.5.26
      - gast==0.5.4
      - google-auth==2.28.1
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.62.0
      - h5py==3.10.0
      - idna==3.6
      - keras==2.14.0
      - libclang==16.0.6
      - markdown==3.5.2
      - markupsafe==2.1.5
      - ml-dtypes==0.2.0
      - numpy==1.26.4
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - packaging==23.2
      - protobuf==4.25.3
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - six==1.16.0
      - tensorboard==2.14.1
      - tensorboard-data-server==0.7.2
      - tensorflow==2.14.0
      - tensorflow-estimator==2.14.0
      - tensorflow-hub==0.15.0
      - tensorflow-io-gcs-filesystem==0.36.0
      - tensorflow-macos==2.14.0
      - termcolor==2.4.0
      - tf-keras==2.15.0
      - typing-extensions==4.10.0
      - urllib3==2.2.1
      - werkzeug==3.0.1
      - wrapt==1.14.1
